function Skeleton() {
  return (
    <div className="space-y-2">
      {[0, 1, 2].map((i) => (
        <div key={i} className="h-3 animate-pulse rounded bg-border" style={{ width: `${90 - i * 12}%` }} />
      ))}
    </div>
  );
}

function RiskNarrative({ narrative, isLoading, isError }) {
  return (
    <div className="rounded-lg border border-border bg-bg p-3">
      {isLoading && <Skeleton />}
      {!isLoading && narrative && (
        <blockquote className="text-sm leading-relaxed text-text-primary">{narrative}</blockquote>
      )}
      {!isLoading && !narrative && (
        <p className="text-sm text-text-secondary">
          {isError
            ? "AI narrative unavailable — the analysis service could not be reached."
            : "AI narrative requires the deployed API with a configured GEMINI_API_KEY."}
        </p>
      )}
      <div className="mt-2 text-[11px] text-text-secondary">Generated by Gemini · SECO risk model</div>
    </div>
  );
}

export default RiskNarrative;
